services:
  res-postgres:
    image: postgres:14-alpine
    container_name: res-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=res
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d res" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8888:5432"
    volumes:
      - ./data-res-postgres/:/var/lib/postgresql/data